hatsu/models.py
from hatsu import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return Register.query.get(int(user_id))


class Scraped(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    thumblist = db.Column(db.Text, unique=True, nullable=False)
    titlelist = db.Column(db.Text, unique=True, nullable=False)
    coverimg = db.Column(db.Text, unique=True, nullable=False)
    description = db.Column(db.Text, unique=True, nullable=False)

    def __repr__(self):
        return f"scrape('{self.thumblist}','{self.titlelist}','{self.coverimg}','{self.description}')"


class Register(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(30), unique=True, nullable=False)
    password = db.Column(db.String(30), unique=True, nullable=False)

    def __repr__(self):
        return f"Register('{self.email}','{self.password}')"

class Fan(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Text, nullable=False)
    content = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"FanFiction('{self.title}','{self.content}')"

hatsu/userpckg/forms.py
from flask_wtf import FlaskForm
from wtforms import validators, StringField, PasswordField, TextAreaField
from wtforms.validators import DataRequired, EqualTo, Email, ValidationError, Length


class Registerform(FlaskForm):
    email = StringField(validators=[DataRequired(), Email()]) 
    password = PasswordField(validators=[DataRequired(), Length(min=2,max=30)])
    confirm_pw = PasswordField(validators=[DataRequired(), EqualTo('password')])

class Loginform(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()]) 
    password = PasswordField('Password', validators=[DataRequired(), Length(min=2,max=30)])

class Fanform(FlaskForm):
     title = TextAreaField(validators=[DataRequired()])
     content = TextAreaField(validators=[DataRequired(), Length(min=5, max=2500)])

    

hatsu/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

app = Flask(__name__)
app.config['SECRET_KEY'] = 'epk'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db'
db  = SQLAlchemy(app)
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
login_manager.login_view = 'users.login'

from hatsu import routes
from hatsu.userpckg.routes import users
from hatsu.basepckg.routes import base

app.register_blueprint(users)
app.register_blueprint(base)

hatsu/basepckg/__init__.py
#

hatsu/basepckg/routes.py
from flask import Blueprint
from flask import render_template, url_for, redirect

base = Blueprint('base',__name__)

hatsu/routes.py
from flask import Flask, render_template
from hatsu import app

@app.route('/')
def home():
    return render_template('home.html')

hatsu/userpckg/__init__.py
#

hatsu/userpckg/routes.py
from flask import Flask, render_template, url_for, redirect, flash, request
from flask_wtf import validators
from flask import Blueprint
from hatsu.userpckg.forms import Registerform, Loginform, Fanform
from hatsu import db, bcrypt
from hatsu.models import Scraped, Register, Fan
from flask_login import login_user, logout_user, login_required, current_user
users = Blueprint('users', __name__)





@users.route('/signup/', methods=['GET', 'POST'])
def signup():
    form = Registerform()
    taken = None
    if form.validate_on_submit():
        user = Register.query.filter_by(email=form.email.data).first()
        if user:
            taken = "Email already in use"
        else:
            hash_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user = Register(email=form.email.data, password=hash_pw)
            db.session.add(user)
            db.session.commit()
            flash("Successfully created your account. Check out your email to confirm, if you don't mind?")
            return redirect(url_for('users.layout'))
    return render_template('signup.html', form=form, taken=taken)


@users.route('/login/', methods=['GET', 'POST'])
def login():
    form = Loginform()
    incorrect = None
    if form.validate_on_submit():
        user = Register.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for('users.layout'))
        else:
            incorrect = "Email or password incorrect"
    return render_template('login.html', form=form, incorrect=incorrect)


@users.route('/anime/')
def anime():
    page = request.args.get('page', 1, type=int)
    obj = db.session.query(Scraped.thumblist, Scraped.titlelist, Scraped.id).paginate(page=page, per_page=3)
    return render_template('anime.html', obj=obj)


@users.route('/detail/<int:desc_id>')
def detail(desc_id):
    description = db.session.query(Scraped.description).filter_by(id=desc_id).scalar()
    titlelist = db.session.query(Scraped.titlelist).filter_by(id=desc_id).scalar()
    coverimg = db.session.query(Scraped.coverimg).filter_by(id=desc_id).scalar()
    return render_template('detail.html', description=description, titlelist=titlelist, coverimg=coverimg)


@users.route('/layout/')
def layout():
    return render_template('layout.html')


@users.route('/logout/')
def logout():
    logout_user()
    return redirect(url_for('users.home'))

@users.route('/submitfiction', methods=['GET', 'POST'])
def submitfiction():
    form = Fanform()
    if form.validate_on_submit():
        user = Fan.query.filter_by(title=form.title.data).first()
        if user:
            flash('taken')
        else:
            user = Fan(title=form.title.data, content=form.content.data)
            db.session.add(user)
            db.session.commit()
            flash('succesful')
            return redirect(url_for('users.layout'))
    return render_template('submitfiction.html', form=form)


@users.route('/fictionlist/')
def fictionlist():
    user = Fan.query.all()
    return render_template('fictionlist.html', user=user)

@users.route('/viewfanfiction/<int:fiction_id>')
def viewfanfiction(fiction_id):
    view = db.session.query(Fan.title, Fan.content).filter_by(id=fiction_id).first()
    return render_template('viewfanfiction.html', view=view)

hatsu/templates/account.html
{% extends "layout.html" %}

{% block headcontent %}
<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/glacial-indifference" type="text/css"/> 
    <style>
        @import url("../static/account.css");
    </style>
{% endblock headcontent %}

{% block bodycontent %}

<!--
<div class="userbox">
    <ul>
        <li><img class="profilepic" src="{{ image_file }}"></li>
        <li>Username : <span class="accountdet">{{ current_user.username }}</span></li>
        <li>Email : <span class="accountdet"> {{ current_user.email }}</span></li>        
    </ul>
</div>

<div class="signbox">
    <h2>Update</h2>        
    <form action="" method="POST" id="form1">  
        {{ form.hidden_tag() }}  
<!--               USERNAME                            -b->
        {{ form.username.label(class_="form_label") }}
        {{ form.username(class_="form_input")  }}
            {% if form.username.errors %}
                {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            {% endif %}   
    <!--                    EMAIL                       -b->
        {{ form.email.label(class_="form_label") }}
        {{ form.email(class_="form_input")  }}
        {% if form.email.errors %}

            {% for error in form.email.errors %}
                <span>{{ error }}</span>
            {% endfor %}

        {% endif %}
                            
    </form>
    <button type="submit" form="form1">
        Update
    </button>   
</div>
-->

<div class="userbox">
    <form action="" method="POST" id="form1">  
        {{ form.hidden_tag() }}  
            <ul>
                <li><img class="profilepic" src="{{ image_file }}"></li>
                <li>Username : {{ form.username(class_="accountdet") }}   
                    {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                     {% endif %} 

                </li>
              <li>Email : {{ form.email(class_="accountdet")  }}</span></li>  
            </ul>
    </form>
    <button type="submit" form="form1">
        Update
    </button> 

</div>

{% endblock bodycontent %} 

hatsu/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, inital-scale=1.0">

    {% if title %}
        <title>Ameagari - {{ title }}</title>
    {% else %}
        <title>Ameagari</title>
    {% endif %}

    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='layout.css') }}">
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/glacial-indifference" type="text/css"/> 

    {% block headcontent %}{% endblock headcontent %}

</head>

<body>
    <div class="container">
        <img src="/static/animes.jpg" class="logo">
        <nav>          
            <ul>
               <a href="{{ url_for('layout') }}"><li>Home</li> </a>
               <a href="{{ url_for('prose.seeprose') }}"><li>Proses</li></a>               
               <a href="{{ url_for('prose.submitprose') }}"><li>Create</li></a>  
              {% if current_user.is_authenticated %}
                <a href="{{ url_for('users.account') }}" ><li>Account</li></a>
                <a href="{{ url_for('users.logout') }}"><li>Logout</li></a>
              {% else %}
              <a href="{{ url_for('users.login') }}"> <li>Login</li></a>
              <a href="{{ url_for('users.signup') }}"><li>Bestjav</li></a>
              {% endif %}

            </ul>
        </nav>
    </div>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul class="flashes">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    {% endwith %} 


    {% block bodycontent %}
    {% endblock bodycontent %}
</body>
</html>

hatsu/templates/login.html
{% extends "layout.html" %}

{% block headcontent %}
<style>
  @import url("../static/signio.css");
</style>
{% endblock headcontent %}

{% block bodycontent %}

    <div class="signbox">
        <h2>Shinda Sekai Sensen</h2>        
        <form action="" method="POST" id="form1" enctype="multipart/form-data">  
            {{ form.hidden_tag() }}  

    <!--               USERNAME                            -->
            {{ form.username.label(class_="form_label") }}
            {{ form.username(class_="form_input")  }}
                {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                {% endif %}   

        <!--          PASSWORD         -->

            {{ form.password.label(class_="form_label") }}
            {{ form.password(class_="form_input")  }}
            {% if form.password.errors %}

                {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                {% endfor %}

            {% endif %}

         <!--{{ form.submit }} -->
            <!--
            <label class="form_label" for="username">Username</label>
            <input class="form_input" type="text" id="username" name="ussy">
            <label class="form_label" for="passy">Password</label>
            <input class="form_input" name="password" id="passy" type="password">
            -->

        </form>
        <button type="submit" form="form1">
            Login
        </button>   
    </div>

{% endblock bodycontent %}

hatsu/templates/seeprose.html
{% extends "layout.html" %}

{% block headcontent %}
    <style>
        .flashes{
            font-size:1em;
        }
    </style>
{% endblock headcontent %}

{% block bodycontent %}

{% for i in user %}
<div class="flashes">
<div> <a href="{{ url_for('prose.diff', prose_id = i.id ) }}" > {{ i.title }} </a></div><hr>
<div> {{ i.prose }} </div>
</div>
{% endfor %}

{% endblock bodycontent %}

hatsu/templates/signup.html
{% extends "layout.html" %}
    {% block headcontent %}
        <style>
            @import url("../static/signio.css");
        </style>
    {% endblock headcontent %}
{% block bodycontent %}

    <div class="signbox">
        <h2>Shinda Sekai Sensen</h2>        
        <form action="" method="POST" id="form1">  
            {{ form.hidden_tag() }}  
    <!--               USERNAME                            -->
            {{ form.username.label(class_="form_label") }}
            {{ form.username(class_="form_input")  }}
                {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                {% endif %}   
        <!--                    EMAIL                       -->
            {{ form.email.label(class_="form_label") }}
            {{ form.email(class_="form_input")  }}
            {% if form.email.errors %}

                {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                {% endfor %}

            {% endif %}
        <!--          PASSWORD         -->

            {{ form.password.label(class_="form_label") }}
            {{ form.password(class_="form_input")  }}
            {% if form.password.errors %}

                {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                {% endfor %}

            {% endif %}
     <!--         CONFIRM PASSWORD         -->   

         {{ form.confirm_password.label(class_="form_label") }}
         {{ form.confirm_password(class_="form_input")  }}
         {% if form.confirm_password.errors %}

             {% for errdor in form.confirm_password.errors %}
                 <span>{{ errdor + 'gayyy'}}</span>
             {% endfor %}
         {% endif %}

         <!--{{ form.submit }} -->
            <!--
            <label class="form_label" for="username">Username</label>
            <input class="form_input" type="text" id="username" name="ussy">
            <label class="form_label" for="passy">Password</label>
            <input class="form_input" name="password" id="passy" type="password">
            -->

        </form>
        <button type="submit" form="form1">
            Login
        </button>   
    </div>

{% endblock bodycontent %}

hatsu/templates/struggle.html
{% extends "layout.html" %}

{% block headcontent %}
    <style>
        .flashes{
            font-size:1em;
        }
    </style>
{% endblock headcontent %}

{% block bodycontent %}

<div class="flashes">
<div> {{ user.title }} </div><hr>
<div> {{ user.prose }} </div>
</div>

{% endblock bodycontent %}

hatsu/templates/submitprose.html
{% extends "layout.html" %}

{% block headcontent %}
<style>
    @import url("../static/signio.css");
    .mypostheight{
        height: 10em;
    }
</style>
{% endblock headcontent %}

{% block bodycontent %}
<div class="signbox">
<form id="form1" action="" method="POST">
    {{ form.hidden_tag() }} 
        <div>Title {{ form.title }} {% if form.title.errors %}
            {% for error in form.title.errors %}
                <span>{{ error }}</span>
             {% endfor %}
             {% endif %} 
        </div>
        <div>Prose {{ form.prose(class_="mypostheight") }}
            {% if form.prose.errors %}
            {% for error in form.prose.errors %}
                <span>{{ error }}</span>
             {% endfor %}
             {% endif %} 
        </div>
</form>

<button type="submit" form="form1">
    Submit Prose
</button>
</div>
{% endblock bodycontent %}